### ISSUE TITLE
cannot import name 'TagKey' from 'ray._private.usage.usage_lib' 

### ISSUE THREAD

**Issue by zdx3578** [NeuromorphicComputing/STPN#4]
(pongSTPN) ➜  AtariMujoco git:(master) ✗ python run-pong.py
Traceback (most recent call last):
  File "/home/jz/github/STPN/AtariMujoco/run-pong.py", line 10, in <module>
    from rllib_nets import TorchMLP_RNNModel, TorchDiagGaussianClipped
  File "/home/jz/github/STPN/AtariMujoco/rllib_nets.py", line 26, in <module>
    from ray.rllib.algorithms import ppo
  File "/home/jz/.conda/envs/pongSTPN/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/__init__.py", line 1, in <module>
    from ray.rllib.algorithms.ppo.ppo import PPOConfig, PPO, DEFAULT_CONFIG
  File "/home/jz/.conda/envs/pongSTPN/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 17, in <module>
    from ray.rllib.algorithms.algorithm import Algorithm
  File "/home/jz/.conda/envs/pongSTPN/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 32, in <module>
    from ray._private.usage.usage_lib import TagKey, record_extra_usage_tag
ImportError: cannot import name 'TagKey' from 'ray._private.usage.usage_lib' (/home/jz/.conda/envs/pongSTPN/lib/python3.9/site-packages/ray/_private/usage/usage_lib.py)
(pongSTPN) ➜  AtariMujoco git:(master) ✗ conda list|grep ray
bitarray                  2.3.0            py39h7f8727e_1  
ray                       2.0.0.dev0               pypi_0    pypi
xarray                    0.20.1             pyhd8ed1ab_0    conda-forge
(pongSTPN) ➜  AtariMujoco git:(master) ✗

**Comment by hector-gr** [comment]
That is certainly quite weird. However it seems to be an error thrown within rllib. Perhaps some dependencies are missing. Did you install `pip install ray[rllib]` after bulding ray, as described in https://github.com/NeuromorphicComputing/STPN/tree/master/AtariMujoco#dependencies ?
